'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''
<Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(2),  _
 Global.System.Security.Permissions.PermissionSetAttribute(Global.System.Security.Permissions.SecurityAction.Demand, Name:="FullTrust")>  _
Partial Public NotInheritable Class Dashboard
    Inherits Microsoft.Office.Tools.Excel.WorksheetBase
    
    Friend WithEvents CAccountCell As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents MarginCell As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents MarginPercCell As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents maxMarginCell As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents IPCell As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents APCell As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents TPVCell As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents TaTPVCell As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents TECell As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents TEPercCell As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents CurrentDateCell As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents TrackingChartLO As Microsoft.Office.Tools.Excel.ListObject
    
    Friend WithEvents TrackingChart As Microsoft.Office.Tools.Excel.Chart
    
    Friend WithEvents TPVatStartCell As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents InterestSLTCell As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents TypeCell As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents SymbolCell As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents StrikeCell As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents DeltaCell As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents QtyCell As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents PriceCell As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents TransCostCell As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents TotValueCell As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents CAccountATCell As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents MarginATCell As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents TeamCell As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents SecondsCell As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents UnderlierRange As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents FamilyDeltaRange As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents RecommendationRange As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents SymbolRange As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents QtyRange As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents VolatilityRange As Microsoft.Office.Tools.Excel.NamedRange
    
    Friend WithEvents TickerCBox As Microsoft.Office.Tools.Excel.Controls.ComboBox
    
    Friend WithEvents StockQtyTBox As Microsoft.Office.Tools.Excel.Controls.TextBox
    
    Friend WithEvents BuyStockButton As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents SellStockButton As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents SellShortStockButton As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents CashDivButton As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents ExecuteStockTransactionButton As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents SymbolCBox As Microsoft.Office.Tools.Excel.Controls.ComboBox
    
    Friend WithEvents OptionQtyTBox As Microsoft.Office.Tools.Excel.Controls.TextBox
    
    Friend WithEvents BuyOptionButton As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents SellOptionButton As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents SellShortOptionButton As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents ExerciseOptionButton As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents ExecuteOptionTransactionButton As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents AlgoTransactionsLogTBox As Microsoft.Office.Tools.Excel.Controls.TextBox
    
    Friend WithEvents Trade0Button As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents Trade1Button As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents Trade2Button As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents Trade3Button As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents Trade4Button As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents Trade5Button As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents Trade6Button As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents Trade7Button As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents Trade8Button As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents Trade9Button As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents Trade10Button As Microsoft.Office.Tools.Excel.Controls.Button
    
    Friend WithEvents Trade11Button As Microsoft.Office.Tools.Excel.Controls.Button
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Public Sub New(ByVal factory As Global.Microsoft.Office.Tools.Excel.Factory, ByVal serviceProvider As Global.System.IServiceProvider)
        MyBase.New(factory, serviceProvider, "Sheet1", "Sheet1")
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Protected Overrides Sub Initialize()
        MyBase.Initialize
        Globals.Dashboard = Me
        Global.System.Windows.Forms.Application.EnableVisualStyles
        Me.InitializeCachedData
        Me.InitializeControls
        Me.InitializeComponents
        Me.InitializeData
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Protected Overrides Sub FinishInitialization()
        Me.OnStartup
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Protected Overrides Sub InitializeDataBindings()
        Me.BeginInitialization
        Me.BindToData
        Me.EndInitialization
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Private Sub InitializeCachedData()
        If (Me.DataHost Is Nothing) Then
            Return
        End If
        If Me.DataHost.IsCacheInitialized Then
            Me.DataHost.FillCachedData(Me)
        End If
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Private Sub InitializeData()
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Private Sub BindToData()
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Private Sub StartCaching(ByVal MemberName As String)
        Me.DataHost.StartCaching(Me, MemberName)
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Private Sub StopCaching(ByVal MemberName As String)
        Me.DataHost.StopCaching(Me, MemberName)
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Private Function IsCached(ByVal MemberName As String) As Boolean
        Return Me.DataHost.IsCached(Me, MemberName)
    End Function
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Private Sub BeginInitialization()
        Me.BeginInit
        Me.CAccountCell.BeginInit
        Me.MarginCell.BeginInit
        Me.MarginPercCell.BeginInit
        Me.maxMarginCell.BeginInit
        Me.IPCell.BeginInit
        Me.APCell.BeginInit
        Me.TPVCell.BeginInit
        Me.TaTPVCell.BeginInit
        Me.TECell.BeginInit
        Me.TEPercCell.BeginInit
        Me.CurrentDateCell.BeginInit
        Me.TrackingChartLO.BeginInit
        Me.TrackingChart.BeginInit
        Me.TPVatStartCell.BeginInit
        Me.InterestSLTCell.BeginInit
        Me.TypeCell.BeginInit
        Me.SymbolCell.BeginInit
        Me.StrikeCell.BeginInit
        Me.DeltaCell.BeginInit
        Me.QtyCell.BeginInit
        Me.PriceCell.BeginInit
        Me.TransCostCell.BeginInit
        Me.TotValueCell.BeginInit
        Me.CAccountATCell.BeginInit
        Me.MarginATCell.BeginInit
        Me.TeamCell.BeginInit
        Me.SecondsCell.BeginInit
        Me.UnderlierRange.BeginInit
        Me.FamilyDeltaRange.BeginInit
        Me.RecommendationRange.BeginInit
        Me.SymbolRange.BeginInit
        Me.QtyRange.BeginInit
        Me.VolatilityRange.BeginInit
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Private Sub EndInitialization()
        Me.VolatilityRange.EndInit
        Me.QtyRange.EndInit
        Me.SymbolRange.EndInit
        Me.RecommendationRange.EndInit
        Me.FamilyDeltaRange.EndInit
        Me.UnderlierRange.EndInit
        Me.SecondsCell.EndInit
        Me.TeamCell.EndInit
        Me.MarginATCell.EndInit
        Me.CAccountATCell.EndInit
        Me.TotValueCell.EndInit
        Me.TransCostCell.EndInit
        Me.PriceCell.EndInit
        Me.QtyCell.EndInit
        Me.DeltaCell.EndInit
        Me.StrikeCell.EndInit
        Me.SymbolCell.EndInit
        Me.TypeCell.EndInit
        Me.InterestSLTCell.EndInit
        Me.TPVatStartCell.EndInit
        Me.TrackingChart.EndInit
        Me.TrackingChartLO.EndInit
        Me.CurrentDateCell.EndInit
        Me.TEPercCell.EndInit
        Me.TECell.EndInit
        Me.TaTPVCell.EndInit
        Me.TPVCell.EndInit
        Me.APCell.EndInit
        Me.IPCell.EndInit
        Me.maxMarginCell.EndInit
        Me.MarginPercCell.EndInit
        Me.MarginCell.EndInit
        Me.CAccountCell.EndInit
        Me.EndInit
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Private Sub InitializeControls()
        Me.CAccountCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CAccountCell", "CAccountCell", Me)
        Me.MarginCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "MarginCell", "MarginCell", Me)
        Me.MarginPercCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "MarginPercCell", "MarginPercCell", Me)
        Me.maxMarginCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "maxMarginCell", "maxMarginCell", Me)
        Me.IPCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "IPCell", "IPCell", Me)
        Me.APCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "APCell", "APCell", Me)
        Me.TPVCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "TPVCell", "TPVCell", Me)
        Me.TaTPVCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "TaTPVCell", "TaTPVCell", Me)
        Me.TECell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "TECell", "TECell", Me)
        Me.TEPercCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "TEPercCell", "TEPercCell", Me)
        Me.CurrentDateCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CurrentDateCell", "CurrentDateCell", Me)
        Me.TrackingChartLO = Globals.Factory.CreateListObject(Nothing, Nothing, "Sheet1:TrackingChartLO", "TrackingChartLO", Me)
        Me.TrackingChart = Globals.Factory.CreateChart(Nothing, Nothing, "Sheet1:Chart 3", "TrackingChart", Me)
        Me.TPVatStartCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "TPVatStartCell", "TPVatStartCell", Me)
        Me.InterestSLTCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "InterestSLTCell", "InterestSLTCell", Me)
        Me.TypeCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "TypeCell", "TypeCell", Me)
        Me.SymbolCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "SymbolCell", "SymbolCell", Me)
        Me.StrikeCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "StrikeCell", "StrikeCell", Me)
        Me.DeltaCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "DeltaCell", "DeltaCell", Me)
        Me.QtyCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "QtyCell", "QtyCell", Me)
        Me.PriceCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "PriceCell", "PriceCell", Me)
        Me.TransCostCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "TransCostCell", "TransCostCell", Me)
        Me.TotValueCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "TotValueCell", "TotValueCell", Me)
        Me.CAccountATCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "CAccountATCell", "CAccountATCell", Me)
        Me.MarginATCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "MarginATCell", "MarginATCell", Me)
        Me.TeamCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "TeamCell", "TeamCell", Me)
        Me.SecondsCell = Globals.Factory.CreateNamedRange(Nothing, Nothing, "SecondsCell", "SecondsCell", Me)
        Me.UnderlierRange = Globals.Factory.CreateNamedRange(Nothing, Nothing, "UnderlierRange", "UnderlierRange", Me)
        Me.FamilyDeltaRange = Globals.Factory.CreateNamedRange(Nothing, Nothing, "FamilyDeltaRange", "FamilyDeltaRange", Me)
        Me.RecommendationRange = Globals.Factory.CreateNamedRange(Nothing, Nothing, "RecommendationRange", "RecommendationRange", Me)
        Me.SymbolRange = Globals.Factory.CreateNamedRange(Nothing, Nothing, "SymbolRange", "SymbolRange", Me)
        Me.QtyRange = Globals.Factory.CreateNamedRange(Nothing, Nothing, "QtyRange", "QtyRange", Me)
        Me.VolatilityRange = Globals.Factory.CreateNamedRange(Nothing, Nothing, "VolatilityRange", "VolatilityRange", Me)
        Me.TickerCBox = New Microsoft.Office.Tools.Excel.Controls.ComboBox(Globals.Factory, Me.ItemProvider, Me.HostContext, "17D50A7511C02014CD21982512CA9CC756A4F1", "17D50A7511C02014CD21982512CA9CC756A4F1", Me, "TickerCBox")
        Me.StockQtyTBox = New Microsoft.Office.Tools.Excel.Controls.TextBox(Globals.Factory, Me.ItemProvider, Me.HostContext, "2525A930024F01243632BC4B265B6B27C79842", "2525A930024F01243632BC4B265B6B27C79842", Me, "StockQtyTBox")
        Me.BuyStockButton = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "33600FB0432AC3347E33AA7F39E20C0CBF55D3", "33600FB0432AC3347E33AA7F39E20C0CBF55D3", Me, "BuyStockButton")
        Me.SellStockButton = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "4C2EDB18241492440654A77445B35F0E456B54", "4C2EDB18241492440654A77445B35F0E456B54", Me, "SellStockButton")
        Me.SellShortStockButton = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "501A385EA5E62D542A75BA8B5D596C6EBC9025", "501A385EA5E62D542A75BA8B5D596C6EBC9025", Me, "SellShortStockButton")
        Me.CashDivButton = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "6455B44C36FCFD64ECB69DFE6CE3A8B42AC736", "6455B44C36FCFD64ECB69DFE6CE3A8B42AC736", Me, "CashDivButton")
        Me.ExecuteStockTransactionButton = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "7396F64A872D87740C67A6477FC0179863EF87", "7396F64A872D87740C67A6477FC0179863EF87", Me, "ExecuteStockTransactionButton")
        Me.SymbolCBox = New Microsoft.Office.Tools.Excel.Controls.ComboBox(Globals.Factory, Me.ItemProvider, Me.HostContext, "8F3F70E5A831CF84F1188F51875C6517EB5508", "8F3F70E5A831CF84F1188F51875C6517EB5508", Me, "SymbolCBox")
        Me.OptionQtyTBox = New Microsoft.Office.Tools.Excel.Controls.TextBox(Globals.Factory, Me.ItemProvider, Me.HostContext, "96C6DD5479008194E449BB5A9E0046AB6F6789", "96C6DD5479008194E449BB5A9E0046AB6F6789", Me, "OptionQtyTBox")
        Me.BuyOptionButton = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "1A69D0E8E13DF814D5D1AB191E368CA49AA8F1", "1A69D0E8E13DF814D5D1AB191E368CA49AA8F1", Me, "BuyOptionButton")
        Me.SellOptionButton = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "13E11F41A1038F1473B1B8DB17B1C167225721", "13E11F41A1038F1473B1B8DB17B1C167225721", Me, "SellOptionButton")
        Me.SellShortOptionButton = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "14CC7416C12ADE1476E199FA10B19E1F2982C1", "14CC7416C12ADE1476E199FA10B19E1F2982C1", Me, "SellShortOptionButton")
        Me.ExerciseOptionButton = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "138E690321D4C214EDB193611D3859C7553D01", "138E690321D4C214EDB193611D3859C7553D01", Me, "ExerciseOptionButton")
        Me.ExecuteOptionTransactionButton = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "1586AF24B1685F147F4197691E9CCE1672C761", "1586AF24B1685F147F4197691E9CCE1672C761", Me, "ExecuteOptionTransactionButton")
        Me.AlgoTransactionsLogTBox = New Microsoft.Office.Tools.Excel.Controls.TextBox(Globals.Factory, Me.ItemProvider, Me.HostContext, "17B7BB04F1D4881482A1979F1562B0CF63DE71", "17B7BB04F1D4881482A1979F1562B0CF63DE71", Me, "AlgoTransactionsLogTBox")
        Me.Trade0Button = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "12E55B82D19F7F14AB21A5C0188362EA005D31", "12E55B82D19F7F14AB21A5C0188362EA005D31", Me, "Trade0Button")
        Me.Trade1Button = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "1EE1E26901D2B414D451BB561AF42A8C0060E1", "1EE1E26901D2B414D451BB561AF42A8C0060E1", Me, "Trade1Button")
        Me.Trade2Button = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "194CFBC661AE78146501A741146C5358905F01", "194CFBC661AE78146501A741146C5358905F01", Me, "Trade2Button")
        Me.Trade3Button = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "1D76BDB941907514F91181E11B58C630A00DB1", "1D76BDB941907514F91181E11B58C630A00DB1", Me, "Trade3Button")
        Me.Trade4Button = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "21131CAA528B64245ED2AE0E2A015C45D52482", "21131CAA528B64245ED2AE0E2A015C45D52482", Me, "Trade4Button")
        Me.Trade5Button = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "2F619F4692E04624C1029E6428FF5076C81252", "2F619F4692E04624C1029E6428FF5076C81252", Me, "Trade5Button")
        Me.Trade6Button = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "2A1D0BFDF221BE24EBD291212A63FBC48784F2", "2A1D0BFDF221BE24EBD291212A63FBC48784F2", Me, "Trade6Button")
        Me.Trade7Button = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "21B1D01222CC8524D682909C2FFFD18FC924C2", "21B1D01222CC8524D682909C2FFFD18FC924C2", Me, "Trade7Button")
        Me.Trade8Button = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "21832559E2749D2490228DD224B6C770684072", "21832559E2749D2490228DD224B6C770684072", Me, "Trade8Button")
        Me.Trade9Button = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "2E53BC42E292B024D8C29DF02866301C7D51F2", "2E53BC42E292B024D8C29DF02866301C7D51F2", Me, "Trade9Button")
        Me.Trade10Button = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "25E35449424FFF24D2A28CD122CF8E5F27F7C2", "25E35449424FFF24D2A28CD122CF8E5F27F7C2", Me, "Trade10Button")
        Me.Trade11Button = New Microsoft.Office.Tools.Excel.Controls.Button(Globals.Factory, Me.ItemProvider, Me.HostContext, "2F996D9E02925624A162AEC824ED8F10833952", "2F996D9E02925624A162AEC824ED8F10833952", Me, "Trade11Button")
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Private Sub InitializeComponents()
        '
        'TickerCBox
        '
        Me.TickerCBox.Name = "TickerCBox"
        Me.TickerCBox.Text = "Select Ticker"
        '
        'StockQtyTBox
        '
        Me.StockQtyTBox.Name = "StockQtyTBox"
        Me.StockQtyTBox.RightToLeft = System.Windows.Forms.RightToLeft.No
        Me.StockQtyTBox.Text = "0"
        Me.StockQtyTBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Right
        '
        'BuyStockButton
        '
        Me.BuyStockButton.BackColor = System.Drawing.SystemColors.Control
        Me.BuyStockButton.ForeColor = System.Drawing.SystemColors.ControlText
        Me.BuyStockButton.Name = "BuyStockButton"
        Me.BuyStockButton.Text = "Buy"
        Me.BuyStockButton.UseVisualStyleBackColor = false
        '
        'SellStockButton
        '
        Me.SellStockButton.BackColor = System.Drawing.SystemColors.Control
        Me.SellStockButton.ForeColor = System.Drawing.SystemColors.ControlText
        Me.SellStockButton.Name = "SellStockButton"
        Me.SellStockButton.Text = "Sell"
        Me.SellStockButton.UseVisualStyleBackColor = false
        '
        'SellShortStockButton
        '
        Me.SellShortStockButton.BackColor = System.Drawing.SystemColors.Control
        Me.SellShortStockButton.ForeColor = System.Drawing.SystemColors.ControlText
        Me.SellShortStockButton.Name = "SellShortStockButton"
        Me.SellShortStockButton.Text = "Sell Short"
        Me.SellShortStockButton.UseVisualStyleBackColor = false
        '
        'CashDivButton
        '
        Me.CashDivButton.BackColor = System.Drawing.SystemColors.Control
        Me.CashDivButton.ForeColor = System.Drawing.SystemColors.ControlText
        Me.CashDivButton.Name = "CashDivButton"
        Me.CashDivButton.Text = "Cash Div"
        Me.CashDivButton.UseVisualStyleBackColor = false
        '
        'ExecuteStockTransactionButton
        '
        Me.ExecuteStockTransactionButton.BackColor = System.Drawing.SystemColors.Control
        Me.ExecuteStockTransactionButton.ForeColor = System.Drawing.SystemColors.ControlText
        Me.ExecuteStockTransactionButton.Name = "ExecuteStockTransactionButton"
        Me.ExecuteStockTransactionButton.Text = "Execute Stock Transaction"
        Me.ExecuteStockTransactionButton.UseVisualStyleBackColor = false
        '
        'SymbolCBox
        '
        Me.SymbolCBox.Name = "SymbolCBox"
        Me.SymbolCBox.Text = "Select Symbol"
        '
        'OptionQtyTBox
        '
        Me.OptionQtyTBox.Name = "OptionQtyTBox"
        Me.OptionQtyTBox.Text = "0"
        Me.OptionQtyTBox.TextAlign = System.Windows.Forms.HorizontalAlignment.Right
        '
        'BuyOptionButton
        '
        Me.BuyOptionButton.BackColor = System.Drawing.SystemColors.Control
        Me.BuyOptionButton.ForeColor = System.Drawing.SystemColors.ControlText
        Me.BuyOptionButton.Name = "BuyOptionButton"
        Me.BuyOptionButton.Text = "Buy"
        Me.BuyOptionButton.UseVisualStyleBackColor = false
        '
        'SellOptionButton
        '
        Me.SellOptionButton.BackColor = System.Drawing.SystemColors.Control
        Me.SellOptionButton.ForeColor = System.Drawing.SystemColors.ControlText
        Me.SellOptionButton.Name = "SellOptionButton"
        Me.SellOptionButton.Text = "Sell"
        Me.SellOptionButton.UseVisualStyleBackColor = false
        '
        'SellShortOptionButton
        '
        Me.SellShortOptionButton.BackColor = System.Drawing.SystemColors.Control
        Me.SellShortOptionButton.ForeColor = System.Drawing.SystemColors.ControlText
        Me.SellShortOptionButton.Name = "SellShortOptionButton"
        Me.SellShortOptionButton.Text = "Sell Short"
        Me.SellShortOptionButton.UseVisualStyleBackColor = false
        '
        'ExerciseOptionButton
        '
        Me.ExerciseOptionButton.BackColor = System.Drawing.SystemColors.Control
        Me.ExerciseOptionButton.ForeColor = System.Drawing.SystemColors.ControlText
        Me.ExerciseOptionButton.Name = "ExerciseOptionButton"
        Me.ExerciseOptionButton.Text = "Exercise"
        Me.ExerciseOptionButton.UseVisualStyleBackColor = false
        '
        'ExecuteOptionTransactionButton
        '
        Me.ExecuteOptionTransactionButton.BackColor = System.Drawing.SystemColors.Control
        Me.ExecuteOptionTransactionButton.ForeColor = System.Drawing.SystemColors.ControlText
        Me.ExecuteOptionTransactionButton.Name = "ExecuteOptionTransactionButton"
        Me.ExecuteOptionTransactionButton.Text = "Execute Option Transaction"
        Me.ExecuteOptionTransactionButton.UseVisualStyleBackColor = false
        '
        'AlgoTransactionsLogTBox
        '
        Me.AlgoTransactionsLogTBox.MaximumSize = New System.Drawing.Size(430, 130)
        Me.AlgoTransactionsLogTBox.MinimumSize = New System.Drawing.Size(430, 130)
        Me.AlgoTransactionsLogTBox.Multiline = true
        Me.AlgoTransactionsLogTBox.Name = "AlgoTransactionsLogTBox"
        Me.AlgoTransactionsLogTBox.ScrollBars = System.Windows.Forms.ScrollBars.Vertical
        '
        'CAccountCell
        '
        Me.CAccountCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'MarginCell
        '
        Me.MarginCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'MarginPercCell
        '
        Me.MarginPercCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'maxMarginCell
        '
        Me.maxMarginCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'IPCell
        '
        Me.IPCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'APCell
        '
        Me.APCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'TPVCell
        '
        Me.TPVCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'TaTPVCell
        '
        Me.TaTPVCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'TECell
        '
        Me.TECell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'TEPercCell
        '
        Me.TEPercCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'CurrentDateCell
        '
        Me.CurrentDateCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'TrackingChartLO
        '
        Me.TrackingChartLO.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'TrackingChart
        '
        Me.TrackingChart.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'TPVatStartCell
        '
        Me.TPVatStartCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'InterestSLTCell
        '
        Me.InterestSLTCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'TypeCell
        '
        Me.TypeCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'SymbolCell
        '
        Me.SymbolCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'StrikeCell
        '
        Me.StrikeCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'DeltaCell
        '
        Me.DeltaCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'QtyCell
        '
        Me.QtyCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'PriceCell
        '
        Me.PriceCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'TransCostCell
        '
        Me.TransCostCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'TotValueCell
        '
        Me.TotValueCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'CAccountATCell
        '
        Me.CAccountATCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'MarginATCell
        '
        Me.MarginATCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'TeamCell
        '
        Me.TeamCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'SecondsCell
        '
        Me.SecondsCell.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'UnderlierRange
        '
        Me.UnderlierRange.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'FamilyDeltaRange
        '
        Me.FamilyDeltaRange.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'RecommendationRange
        '
        Me.RecommendationRange.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'SymbolRange
        '
        Me.SymbolRange.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'QtyRange
        '
        Me.QtyRange.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        '
        'Trade0Button
        '
        Me.Trade0Button.BackColor = System.Drawing.SystemColors.Control
        Me.Trade0Button.ForeColor = System.Drawing.SystemColors.ControlText
        Me.Trade0Button.Name = "Trade0Button"
        Me.Trade0Button.Text = "[0]"
        Me.Trade0Button.UseVisualStyleBackColor = false
        '
        'Trade1Button
        '
        Me.Trade1Button.BackColor = System.Drawing.SystemColors.Control
        Me.Trade1Button.ForeColor = System.Drawing.SystemColors.ControlText
        Me.Trade1Button.Name = "Trade1Button"
        Me.Trade1Button.RightToLeft = System.Windows.Forms.RightToLeft.No
        Me.Trade1Button.Text = "[1]"
        Me.Trade1Button.UseVisualStyleBackColor = false
        '
        'Trade2Button
        '
        Me.Trade2Button.BackColor = System.Drawing.SystemColors.Control
        Me.Trade2Button.ForeColor = System.Drawing.SystemColors.ControlText
        Me.Trade2Button.Name = "Trade2Button"
        Me.Trade2Button.Text = "[2]"
        Me.Trade2Button.UseVisualStyleBackColor = false
        '
        'Trade3Button
        '
        Me.Trade3Button.BackColor = System.Drawing.SystemColors.Control
        Me.Trade3Button.ForeColor = System.Drawing.SystemColors.ControlText
        Me.Trade3Button.Name = "Trade3Button"
        Me.Trade3Button.Text = "[3]"
        Me.Trade3Button.UseVisualStyleBackColor = false
        '
        'Trade4Button
        '
        Me.Trade4Button.BackColor = System.Drawing.SystemColors.Control
        Me.Trade4Button.ForeColor = System.Drawing.SystemColors.ControlText
        Me.Trade4Button.Name = "Trade4Button"
        Me.Trade4Button.Text = "[4]"
        Me.Trade4Button.UseVisualStyleBackColor = false
        '
        'Trade5Button
        '
        Me.Trade5Button.BackColor = System.Drawing.SystemColors.Control
        Me.Trade5Button.ForeColor = System.Drawing.SystemColors.ControlText
        Me.Trade5Button.Name = "Trade5Button"
        Me.Trade5Button.Text = "[5]"
        Me.Trade5Button.UseVisualStyleBackColor = false
        '
        'Trade6Button
        '
        Me.Trade6Button.BackColor = System.Drawing.SystemColors.Control
        Me.Trade6Button.ForeColor = System.Drawing.SystemColors.ControlText
        Me.Trade6Button.Name = "Trade6Button"
        Me.Trade6Button.Text = "[6]"
        Me.Trade6Button.UseVisualStyleBackColor = false
        '
        'Trade7Button
        '
        Me.Trade7Button.BackColor = System.Drawing.SystemColors.Control
        Me.Trade7Button.ForeColor = System.Drawing.SystemColors.ControlText
        Me.Trade7Button.Name = "Trade7Button"
        Me.Trade7Button.Text = "[7]"
        Me.Trade7Button.UseVisualStyleBackColor = false
        '
        'Trade8Button
        '
        Me.Trade8Button.BackColor = System.Drawing.SystemColors.Control
        Me.Trade8Button.ForeColor = System.Drawing.SystemColors.ControlText
        Me.Trade8Button.Name = "Trade8Button"
        Me.Trade8Button.Text = "[8]"
        Me.Trade8Button.UseVisualStyleBackColor = false
        '
        'Trade9Button
        '
        Me.Trade9Button.BackColor = System.Drawing.SystemColors.Control
        Me.Trade9Button.ForeColor = System.Drawing.SystemColors.ControlText
        Me.Trade9Button.Name = "Trade9Button"
        Me.Trade9Button.Text = "[9]"
        Me.Trade9Button.UseVisualStyleBackColor = false
        '
        'Trade10Button
        '
        Me.Trade10Button.BackColor = System.Drawing.SystemColors.Control
        Me.Trade10Button.ForeColor = System.Drawing.SystemColors.ControlText
        Me.Trade10Button.Name = "Trade10Button"
        Me.Trade10Button.Text = "[10]"
        Me.Trade10Button.UseVisualStyleBackColor = false
        '
        'Trade11Button
        '
        Me.Trade11Button.BackColor = System.Drawing.SystemColors.Control
        Me.Trade11Button.ForeColor = System.Drawing.SystemColors.ControlText
        Me.Trade11Button.Name = "Trade11Button"
        Me.Trade11Button.Text = "[11]"
        Me.Trade11Button.UseVisualStyleBackColor = false
        '
        'VolatilityRange
        '
        Me.VolatilityRange.DefaultDataSourceUpdateMode = System.Windows.Forms.DataSourceUpdateMode.Never
        Me.TickerCBox.BindingContext = Me.BindingContext
        Me.StockQtyTBox.BindingContext = Me.BindingContext
        Me.BuyStockButton.BindingContext = Me.BindingContext
        Me.SellStockButton.BindingContext = Me.BindingContext
        Me.SellShortStockButton.BindingContext = Me.BindingContext
        Me.CashDivButton.BindingContext = Me.BindingContext
        Me.ExecuteStockTransactionButton.BindingContext = Me.BindingContext
        Me.SymbolCBox.BindingContext = Me.BindingContext
        Me.OptionQtyTBox.BindingContext = Me.BindingContext
        Me.BuyOptionButton.BindingContext = Me.BindingContext
        Me.SellOptionButton.BindingContext = Me.BindingContext
        Me.SellShortOptionButton.BindingContext = Me.BindingContext
        Me.ExerciseOptionButton.BindingContext = Me.BindingContext
        Me.ExecuteOptionTransactionButton.BindingContext = Me.BindingContext
        Me.AlgoTransactionsLogTBox.BindingContext = Me.BindingContext
        Me.Trade0Button.BindingContext = Me.BindingContext
        Me.Trade1Button.BindingContext = Me.BindingContext
        Me.Trade2Button.BindingContext = Me.BindingContext
        Me.Trade3Button.BindingContext = Me.BindingContext
        Me.Trade4Button.BindingContext = Me.BindingContext
        Me.Trade5Button.BindingContext = Me.BindingContext
        Me.Trade6Button.BindingContext = Me.BindingContext
        Me.Trade7Button.BindingContext = Me.BindingContext
        Me.Trade8Button.BindingContext = Me.BindingContext
        Me.Trade9Button.BindingContext = Me.BindingContext
        Me.Trade10Button.BindingContext = Me.BindingContext
        Me.Trade11Button.BindingContext = Me.BindingContext
    End Sub
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Private Function NeedsFill(ByVal MemberName As String) As Boolean
        Return Me.DataHost.NeedsFill(Me, MemberName)
    End Function
    
    '''
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Never)>  _
    Protected Overrides Sub OnShutdown()
        Me.VolatilityRange.Dispose
        Me.QtyRange.Dispose
        Me.SymbolRange.Dispose
        Me.RecommendationRange.Dispose
        Me.FamilyDeltaRange.Dispose
        Me.UnderlierRange.Dispose
        Me.SecondsCell.Dispose
        Me.TeamCell.Dispose
        Me.MarginATCell.Dispose
        Me.CAccountATCell.Dispose
        Me.TotValueCell.Dispose
        Me.TransCostCell.Dispose
        Me.PriceCell.Dispose
        Me.QtyCell.Dispose
        Me.DeltaCell.Dispose
        Me.StrikeCell.Dispose
        Me.SymbolCell.Dispose
        Me.TypeCell.Dispose
        Me.InterestSLTCell.Dispose
        Me.TPVatStartCell.Dispose
        Me.TrackingChart.Dispose
        Me.TrackingChartLO.Dispose
        Me.CurrentDateCell.Dispose
        Me.TEPercCell.Dispose
        Me.TECell.Dispose
        Me.TaTPVCell.Dispose
        Me.TPVCell.Dispose
        Me.APCell.Dispose
        Me.IPCell.Dispose
        Me.maxMarginCell.Dispose
        Me.MarginPercCell.Dispose
        Me.MarginCell.Dispose
        Me.CAccountCell.Dispose
        MyBase.OnShutdown
    End Sub
End Class

Partial Friend NotInheritable Class Globals
    
    Private Shared _Dashboard As Dashboard
    
    Friend Shared Property Dashboard() As Dashboard
        Get
            Return _Dashboard
        End Get
        Set
            If (_Dashboard Is Nothing) Then
                _Dashboard = value
            Else
                Throw New System.NotSupportedException()
            End If
        End Set
    End Property
End Class
